language: c
env:
  - OPAM_PACKAGES="ounit oasis"
script:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml opam
  - export OPAMYES=1
  - opam init
  - eval `opam config -env`
  - opam pin ocamlfind git://github.com/whitequark/ocaml-findlib
  - opam install -q -y ${OPAM_PACKAGES}
  - ./configure --enable-tests
  - make test
